- name: playbook level variables
  hosts: web
  become: true
  vars_files:
    - course.yaml
  tasks:
  - name: print course details
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "Course is: {{ COURSE }}, Duration: {{ DURATION }}, Trainer is: {{ TRAINER }}"