- name: conditions example
  hosts: local
  connection: local
  become: true
  vars:
    IS_LIVE: false
  tasks:
  - name: check live or not
    ansible.builtin.debug:
      msg: "This is live environment"
    when: IS_LIVE